### ISSUE TITLE
TypeError: PoolBN.forward: `input` must be present

### ISSUE THREAD

**Issue by huangjiyi** [microsoft/archai#28]
Hello, I have installed Archai follow through tutorial. But when I run `python scripts/main.py --algos darts`,  the following error occurred：
> Traceback (most recent call last):
  File "/home/hjy/PalmNAS/archai/scripts/main.py", line 11, in <module>
    from archai.nas.exp_runner import ExperimentRunner
  File "/home/hjy/PalmNAS/archai/archai/nas/exp_runner.py", line 11, in <module>
    from archai.nas.model_desc_builder import ModelDescBuilder
  File "/home/hjy/PalmNAS/archai/archai/nas/model_desc_builder.py", line 14, in <module>
    from archai.nas.operations import StemBase, Op
  File "/home/hjy/PalmNAS/archai/archai/nas/operations.py", line 133, in <module>
    class PoolBN(Op):
  File "/home/hjy/PalmNAS/archai/archai/nas/operations.py", line 162, in PoolBN
    def forward(self, x):
  File "/home/hjy/miniconda3/envs/nas/lib/python3.9/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/hjy/miniconda3/envs/nas/lib/python3.9/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/home/hjy/miniconda3/envs/nas/lib/python3.9/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/home/hjy/miniconda3/envs/nas/lib/python3.9/site-packages/overrides/signature.py", line 97, in ensure_signature_is_compatible
    ensure_all_positional_args_defined_in_sub(
  File "/home/hjy/miniconda3/envs/nas/lib/python3.9/site-packages/overrides/signature.py", line 211, in ensure_all_positional_args_defined_in_sub
    raise TypeError(f"{method_name}: \`{super_param.name}\` must be present")
TypeError: PoolBN.forward: \`input\` must be present

**Comment by gugarosa** [comment]
Hi @huangjiyi! I hope everything is going well with you.

This is a nasty bug caused by an update on the `overrides` package. Though I am unsure why you probably had its latest version when our `setup.py` explicit tells to install a lower version.

Nevertheless, could you please try the following and check if it fixes your problem?

```
pip uninstall overrides
pip install overrides==3.1.0
```

Thank you and best regards,
Gustavo.

**Comment by huangjiyi** [comment]
Thank you @gugarosa! It works. This bug is indeed a package version problem. And I also don’t know why the version of `overrides` package on my device is `6.1.0`,

**Comment by gugarosa** [comment]
No worries, it also happened to me when I tried with a fresh Python 3.9 environment. I will check why this is happening!

If there is anything else, please just let us know!!
